<footer id="main" class="clearfix">
  <div class="row">
    <div class="medium-6 columns">
      <address>
        The Edith O&rsquo;Donnell Institute of Art History<br>
        The University of Texas at Dallas<br>
        800 W. Campbell Road<br>
        Richardson, TX 75080
      </address>
      <small><a href="tel:+1-972-883-2475">972-883-2475 </a></small>
      <p><small>Copyright &copy; 2015 <a href="/arthistory/">The University of Texas at Dallas</a></small></p>
      </div>
      <div class="medium-6 columns show-for-medium-up">
        <p class="text-right"><a href="/arthistory/arthistory/"><img src="/arthistory/img/odonnell-wordmark.svg" style="opacity:0.65"></a></p>
    </div>
    </div>
</footer>