<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="stylesheet" href="/arthistory/css/foundation.css" />
<link rel="stylesheet" href="/arthistory/css/styles.css" />
<link rel="stylesheet" type="text/css" href="/arthistory/css/print.css" media="print" />
<script src="/arthistory/js/vendor/modernizr.js"></script>
<script src="https://use.typekit.net/aku8pcy.js"></script>
<script>try{Typekit.load({ async: true });}catch(e){}</script>
<meta name="WT.cg_n" content="Art_History"  />