<header class="show-for-small-only center clearfix">
  <div class="row">
    <div class="small-2 columns">
      <a role="button" class="left-off-canvas-toggle show-for-small-only menu-icon" href="#"><img src="/arthistory/img/hamburger.gif" width="20px" style="margin-top: 1rem"></a>
    </div>
    <div class="small-10 columns">
      <a href="/arthistory/"><img src="/arthistory/img/odonnell-wordmark-short.svg"></a>
    </div>
  </div>
  <hr style="margin-bottom:-15px">
</header>

<!-- Off Canvas Menu -->
<aside id="mobile-nav" class="left-off-canvas-menu row">
  <div class="large-12 columns">
    <header>
      <a href="/arthistory/" class="text-right" style="display:block;"><img src="/arthistory/img/odonnell-wordmark-white.svg"></a>
      <a href="http://www.utdallas.edu/"><img src="/arthistory/img/ut-dallas-white.svg" width="120"></a>
    </header>
    <nav>
      <ul>
        <li><a href="/arthistory/about/">About</a>
          <ul>
            <li><a href="/arthistory/welcome/">Director's Welcome</a></li>
            <li><a href="/arthistory/about/">About The O&rsquo;Donnell Institute</a></li>
            <li><a href="/arthistory/partnerships/">Partnerships</a></li>
            <li><a href="/arthistory/contact/">Contact Us</a></li>
            <li><a href="/arthistory/newsletter/">Newsletter</a></li>
          </ul>
        </li>
        <li><a href="/arthistory/graduate/">Academics</a>
          <ul>
            <li><a href="/arthistory/graduate/">Graduate</a></li>
            <li><a href="/arthistory/undergraduate/">Undergraduate</a></li>
            <li><a href="/arthistory/courses/">Courses</a></li>
          </ul>
        </li>
        <li><a href="/arthistory/research/">Research</a>
        </li>

        <li><a href="/arthistory/programs/">Programs</a>
        </li>
        <li><a href="/arthistory/scholars/">People</a>
          <ul>
            <li><a href="/arthistory/scholars/">Scholars</a></li>
            <li><a href="/arthistory/fellows/">Fellows</a></li>
            <li><a href="/arthistory/staff/">Staff</a></li>
          </ul>
        </li>


        <li><a href="/arthistory/contact/">Contact</a></li>
      </ul>
    </nav>
    <footer>
      <address>
            The Edith O&rsquo;Donnell Institute of Art History<br>
            The University of Texas at Dallas<br>
            800 W. Campbell Road<br>
            Richardson, TX 75080
          </address>
      <p><small><a href="tel:+1-972-883-2475">972-883-2475 </a></small></p>
      <p><small>Copyright &copy; 2015 <a href="http://www.utdallas.edu/"><br>The University of Texas at Dallas</a></small></p>
    </footer>
  </div>
</aside>

<!-- main header for tablet + -->
<header id="tablet-header" class="row">
  <div class="medium-5 medium-offset-1 columns hide-for-small-only">
    <a href="http://www.utdallas.edu/"><img src="/arthistory/img/ut-dallas-black.svg" style="opacity:0.8; width: 177px"></a>
  </div>
  <div class="medium-5 columns end hide-for-small-only">
    <p class="text-right">
      <a href="/arthistory/"><img src="/arthistory/img/odonnell-wordmark.svg" style="opacity:0.8"></a>
    </p>
  </div>
</header>

<nav id="tablet-nav" class="show-for-medium-up">
  <ul class="button-group">
    <li><a href="/arthistory/about/" class="button" data-dropdown="about-dropdown" aria-controls="drop2" data-options="is_hover:true" aria-expanded="false">About</a></li>
    <!-- about dropdown -->
    <div id="about-dropdown" data-dropdown-content class="f-dropdown content" aria-hidden="true" tabindex="-1">
      <div class="row">
        <div class="medium-6 columns">
          <ul>
            <li><a href="/arthistory/welcome/">Director's Welcome</a></li>
            <li><a href="/arthistory/about/">About the Institute</a></li>
            <li><a href="/arthistory/partnerships/">Partnerships</a></li>
            <li><a href="/arthistory/contact/">Contact Us</a></li>
            <li><a href="/arthistory/newsletter/">Newsletter</a></li>
          </ul>
        </div>
      </div>
    </div>
    <li><a href="/arthistory/graduate/" class="button" data-dropdown="academics-dropdown" aria-controls="drop2" data-options="is_hover:true" aria-expanded="false">Academics</a></li>
    <!-- Academics dropdown -->
    <div id="academics-dropdown" data-dropdown-content class="f-dropdown content" aria-hidden="true" tabindex="-1">
      <div class="row">
        <div class="medium-6 columns">
          <ul>
            <li><a href="/arthistory/graduate/">Graduate</a></li>
            <li><a href="/arthistory/undergraduate/">Undergraduate</a></li>
            <li><a href="/arthistory/courses/">Courses</a></li>
          </ul>
        </div>
      </div>
    </div>
    <li><a href="/arthistory/research/" class="button" data-dropdown="research-dropdown" aria-controls="drop2" data-options="is_hover:true" aria-expanded="false">Research</a></li>
    <!-- research dropdown -->
    <div id="research-dropdown" data-dropdown-content class="f-dropdown content" aria-hidden="true" tabindex="-1">
      <div class="row">
        <div class="medium-12 columns">
          <ul>
            <li><a href="/arthistory/research/">About Our Research</a></li>
            <li><a href="/arthistory/conservation/">Conservation Science</a></li>
            <li><a href="/arthistory/islamic-art/">Islamic Art History</a></li>
            <li><a href="/arthistory/research/#filter=.documentation">Documentation and Artists as Writers</a></li>
            <li><a href="/arthistory/research/#filter=.art-and-science">Art and Science</a></li>
            <li><a href="/arthistory/census/">Census of French Sculpture</a></li>
          </ul>
        </div>
      </div>
    </div>
    <li><a href="/arthistory/programs/" class="button">Programs</a></li>

    <li><a href="/arthistory/scholars/" class="button" data-dropdown="people-dropdown" aria-controls="drop2" data-options="is_hover:true" aria-expanded="false">People</a></li>
    <!-- people dropdown -->
    <div id="people-dropdown" data-dropdown-content class="f-dropdown content" aria-hidden="true" tabindex="-1">
      <div class="row">
        <div class="medium-6 columns">
          <ul>
            <li><a href="/arthistory/scholars/">Scholars</a></li>
            <li><a href="/arthistory/fellows/">Fellows</a></li>
            <li><a href="/arthistory/staff/">Staff</a></li>
          </ul>
        </div>
      </div>
    </div>
    
    <li><a href="/arthistory/contact/" class="button">Contact</a></li>
    <!--<li>
      <a href="#" class="button">
        <svg id="Layer_1" xmlns="http://www.w3.org/2000/svg" xml:space="preserve" viewBox="0 0 280.321 280.321" width="16px" version="1.1" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" enable-background="new 0 0 280.321 280.321">
          <path clip-rule="evenodd" d="m206.65 184.14c11.734 11.724 23.262 23.257 34.809 34.773 11.436 11.406 22.891 22.795 33.938 33.793-7.545 7.584-14.895 14.975-22.486 22.606-22.514-22.547-45.637-45.704-68.67-68.772-53.538 38.62-120.55 24.024-155.44-20.35-34.577-43.97-31.308-107.39 7.937-147.45 39.561-40.385 102.87-45.003 147.62-11.167 45.45 34.359 61.27 102.38 22.29 156.57zm-169.7-66.97c0.106 44.28 36.017 79.923 80.358 79.757 43.806-0.165 79.767-36.417 79.577-80.226-0.189-44.139-36.332-79.921-80.546-79.741-43.962 0.179-79.492 36.076-79.386 80.211z" fill-rule="evenodd" />
        </svg>
      </a>
    </li>-->
  </ul>
</nav>