<!-- Begin MailChimp Signup Form -->
<div class="row" style="background:#f3f3f3">
  <form action="//utdallas.us4.list-manage.com/subscribe/post?u=c22cb558f1a8fc11b3f63cd54&amp;id=f76fa4299e" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll" class="medium-6 columns"> <br>
      <h6>Subscribe to Our Newsletter</h6>
      <h6 class="subheader">Subscribe to our email newsletter for the latest information about The O&#8217;Donnell Institute.</h6>
      <br>
    </div>
    <br>
    <div class="medium-6 columns"> <br>
      <div class="row collapse postfix">
        <div class="small-9 columns">
          <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
        </div>
        <div class="small-3 columns"> 
          <input type="submit" class="button postfix value="Subscribe" name="subscribe" id="mc-embedded-subscribe" "> 
        </div>
      </div>
    </div>
  </form>
</div>
<!--End mc_embed_signup-->